# https://github.com/wg-easy/wg-easy
services:
  wg-easy:
    environment:
      # Required:
      # Change this to your host's public address
      - WG_HOST=xxx.xxx.xxx.xxx
      - PUID=1000 #UserID
      - PGID=1000 #GroupID
      # Optional:
      - PASSWORD=password
      - WG_PORT=51823
      - WG_DEFAULT_ADDRESS=192.168.1.x
      - WG_DEFAULT_DNS=192.168.0.80
      - WG_MTU=1500
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wireguard
    volumes:
      - /home/docker-volumes/wireguard:/etc/wireguard
    ports:
      - "51823:51820/udp" # Zugriff von außen -> muss am Router eingestellt werden (Port-forwarding)
      - "51821:51821/tcp" # Zugriff auf Webseite
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
